remote_theme: DrCyberNinja/space-jekyll-template

#Site Settings
desctiption: 
baseurl: /
url: 'https://drcyberninja.github.io'

#UserSettings
username: DrCyberNinja
email: paige@sconzo.io
twitter_username: DrCyberNinja
github_username: DrCyberNinja
linkedin_public_url: www.linkedin.com/in/jdoc


#Links to include in menu navigation
links:
  section_1:
    - title: home
      url: /
      key_trigger: 1
    - title: my posts
      url: /posts
      key_trigger: 2
    - title: resume
      url: /resume
      key_trigger: 3
    - title: about me
      url: /about
      key_trigger: 4
  section_2:
    - title: github
      url: http://www.github.com/DrCyberNinja
      new_tab: true
      key_trigger: g
    - title: twitter
      url: http://wwww.twitter.com/drcyberninja
      key_trigger: t
    - title: search
      url: ""
      key_trigger: s
