remote_theme: DrCyberNinja/space-jekyll-template

#Site Settings
desctiption: 
baseurl: "/"
url: "https://drcyberninja.github.io"

#UserSettings
username: DrCyberNinja
email: paige@sconzo.io
twitter_username: DrCyberNinja
github_username: DrCyberNinja
